# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PS_9201080N0118.xdc

# Block Designs: bd/PS_9201080N0118/PS_9201080N0118.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_9201080N0118 || ORIG_REF_NAME==PS_9201080N0118} -quiet] -quiet

# IP: bd/PS_9201080N0118/ip/PS_9201080N0118_processing_system7_0_0/PS_9201080N0118_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_9201080N0118_processing_system7_0_0 || ORIG_REF_NAME==PS_9201080N0118_processing_system7_0_0} -quiet] -quiet

# XDC: bd/PS_9201080N0118/PS_9201080N0118_ooc.xdc
