# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lenovo/Desktop/HCD/PS_9201080N0118_9201080N0139/PS_9201080N0118_9201080N0139.srcs/sources_1/bd/PS_9201080N0118/ip/PS_9201080N0118_processing_system7_0_0/PS_9201080N0118_processing_system7_0_0.xci
# IP: The module: 'PS_9201080N0118_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lenovo/Desktop/HCD/PS_9201080N0118_9201080N0139/PS_9201080N0118_9201080N0139.srcs/sources_1/bd/PS_9201080N0118/ip/PS_9201080N0118_processing_system7_0_0/PS_9201080N0118_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_9201080N0118_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/lenovo/Desktop/HCD/PS_9201080N0118_9201080N0139/PS_9201080N0118_9201080N0139.srcs/sources_1/bd/PS_9201080N0118/ip/PS_9201080N0118_processing_system7_0_0/PS_9201080N0118_processing_system7_0_0.xci
# IP: The module: 'PS_9201080N0118_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lenovo/Desktop/HCD/PS_9201080N0118_9201080N0139/PS_9201080N0118_9201080N0139.srcs/sources_1/bd/PS_9201080N0118/ip/PS_9201080N0118_processing_system7_0_0/PS_9201080N0118_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_9201080N0118_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
